# This script generates Figure 4
#
# It uses "metabolomics_datasets.Rdata", which is generated by 
# `data_hc_hits_analysis.R`
#
# The execution takes about 140s on an Apple M1 Pro


rm(list = ls())
library(magrittr)
library(survival)
library(ggplot2)
library(rox)

# load preprocessed datasets
load("metabolomics_datasets.Rdata")

# set names of datasets   
v = names(datasets) 

# prepare the data for high-confidence hits analysis
ldata <-
  lapply(structure(v, names = v), function(name_data){
    print(name_data)
    
    # outcome 
    y = as.numeric(datasets[[name_data]]$groups)
  
    # at least %10 or n=20 complete cases should be in
    # this is to make sure HC hits are decided with enough power
    max_missingness_allowed =  max( 0.1*length(y), 20 )
    
    # data raw
    X = datasets[[name_data]]$X
    # drop metabolites which have too many missing  values 
    # print(table(colSums(!is.na(X)) >= max_missingness_allowed ) %>% {./sum(.)})
    X = X[,colSums(!is.na(X)) >= max_missingness_allowed ]
    X = X[,order(colSums( is.na(X) ))]
    
    # if there is an outlier effect, ignore those
    # direction of high confidence hits is important 
    # this is the ensure that effect direction is not due to only some samples 
    jinds = which( 
      (sign(cor(X,y, use = "pair") ) == sign( cor(X,y, use = "pair", method = "kendall") )) == F 
    )
 
    if(length(jinds)>0){
      X = X[,-jinds]
    }
    # min-imputen and knn-imputed data 
    Xmip = datasets[[name_data]]$X.minimp[,colnames(X)] 
    Xknn = datasets[[name_data]]$X.knnimp[,colnames(X)] 
    
    list(x= X, xknn = Xknn, xmip = Xmip, y=y)
  })
  

# wrapper functions for each specific test
fisher_wrap <- function(x,y){
  ft = try( fisher.test(table(!is.na(x),y)), silent = T)
  
  if(inherits(ft,"try-error")) c(p = NA, est = NA)
  else c(p = unname(ft$p.value), est = unname( log(ft$estimate) ))
}

wilcox_wrap <- function(x,y){
  wi = try( wilcox.test(x~y), silent = T)
  # OR identically
  # wi = try( cor.test(x,y, method ="kendall", use ="pair") )
  
  # mann-witney U similar do sommers D which is similar to kendall tau 
  # that can be used as an effect size estimate for wilcox 
  # this is to decide effect direction
  
  if(inherits(wi,"try-error")) c(p = NA, est = NA)
  else c(p = unname(wi$p.value), est = 2*(concordance(y~x)$concordance-0.5) )
}

roxtest_wrap <- function(x,y){
  rr = try( rox(x, y), silent = T)
  
  if(inherits(rr,"try-error")) return( c(p = NA, est = NA) )
  structure( c(p = unname(rr$stats["p"]), est = unname( 2*rr$stats["d"]-1 )), plod = rr$w )
}

# determine HC-hits based on wilcox p-value, direction 
# and fisher test p-value and direction
# the group that has more missing values should have 
# average lower metabolite abundances 
# fisher test here is one-sided, because it tests LOD
# tp: wilcox p-value
# fp: fisher test p-value
hit_decider <- function(tp, td, fp, fd, pth = 0.05){
  if(is.na(tp)) tp =1
  if(is.na(fp)) fp =1
  
  if( ((tp < pth) & (sign(td)!=sign(fd))) | (tp < fp) ) 
    return(data.frame(p =tp, est = td, test = "tt" ))
  
  return(data.frame(p = fp, est = fd, test = "ft" ))
}
  
# analysis wrapper function
# the exact same analysis will be performed for each datasets 
fanaly <- function(nod){
  # data
  X = nod$x
  Xmin = nod$xmip[,colnames(X)]
  Xknn = nod$xknn[,colnames(X)]
  # outcome
  y = nod$y
  # wilcox and fisher to decide high confidence hits 
  # HC hits are those that are significant based on wilcox test, or
  # those that are significant in one sided fisher test
  re0 = 
    apply(X,2, function(xh) lapply(
      list(fisher = fisher_wrap, wilcox = wilcox_wrap), 
      function(f) f(xh,y))
    )
  
  # get p-values and estimations (effect sizes)
  re0_pval = sapply(re0,sapply,`[`, "p") %>% t %>% data.frame
  re0_stat = sapply(re0,sapply,`[`, "est") %>% t %>% data.frame

  # decide the high confidence hits
  sm=
    lapply( rownames(re0_stat), function(i)
      cbind(
        hit_decider( re0_pval[i,"wilcox.p"], re0_stat[i,"wilcox.est"], 
                     re0_pval[i,"fisher.p"], re0_stat[i,"fisher.est"]),
        met = i )
    ) %>% do.call(what = rbind)
  sm$miss = colSums(is.na(X))/nrow(X)
  
  # order w.r.t. p-values 
  sm = sm[order(sm$p),]
  
  # here we calculate p-values for CCA, after knn, min imputation, and for rox
  re1 =
    lapply(structure(colnames(X), names = colnames(X) ), function(i){
      # metabolite
      # i = "S-adenosylmethionine (SAM)"#"xanthosine" #"hippurate"
      x = X[,i]
      xmin = Xmin[,i]
      xknn = Xknn[,i]
      
      list(
        wt_minp = wilcox_wrap(xmin, y),
        wt_knn = wilcox_wrap(xknn, y),
        rox = roxtest_wrap(x, y),
        miss = sum(is.na(x))/length(x)
      )
    })
  
  list( sm=sm, re0=re0, re1=re1 )
}
  
# wrapper function to get plottable data
get_plottable_data <- function(rop, pmin = 1e-10, pmax = 0.05, padjust = T){
  
  # calculate rate of HC hits recovert for top-N
  calculate_tpr <- function(ph, sm, K=0.1, mth = -1, padjust = T){ #K=nrow(sm)/2
    ph = ph[, sm$met[sm$miss>mth], drop = F]
    sm = sm[sm$miss>mth, ,drop = F]
    if(padjust){
      ph["p",] = p.adjust(ph["p",], "fdr")
      sm$p = p.adjust(sm$p, "fdr")
    }
    # adaptive desicion
    if(K< 1){
      K = sum(sm$p < K)
      print(K)
    }
    sapply( seq( K ), function(k){
      pth = sm[k,"p"]
      mets = sm$met[seq(k)]
      dest = sm$est[seq(k)] # directions 
      # to be compared with
      p2= ph[,mets,drop = F]
      h = (p2["p",] <= pth)*(sign(p2["est",]) == sign(dest))
      c( found = sum(h,na.rm = T), all = length(h))
    }) %>% t %>% {data.frame(.,p = sm$p[seq(K)])}
  }

  raa = with(rop, lapply(names(re1[[1]])[-length(re1[[1]])] %>% structure(., names =.), function(j)
    calculate_tpr( sapply(re1,`[[`, j), sm, mth = 0, padjust = padjust, K = pmax )) ) 
  
  mm = sapply(raa, `[[`, "found")
  data.frame(mm, n = seq(nrow(mm)),  pv = raa[[1]]$p) %>% {.[.$pv> pmin,]}
}

# perform analysis for each datasets
ldf<- lapply(names(ldata), function(i){
  rop = fanaly(ldata[[i]])
  
  df = get_plottable_data(rop, pmin = 1e-11, pmax = 0.1, padjust = T)
  
  # pvalue thresholds to decide the significant metabolites
  pval_thresholds = c(0.1, 0.05, 0.01, 0.001, 1e-5, 1e-10)
  df2 = sapply( pval_thresholds, function(pth) 
    c( n= max(df[df$pv<=pth, "n"]), p =pth) ) %>% t %>% data.frame()
  
  df$dt <- df2$dt <- i
  list(df=df, df2=df2)
})
names(ldf) = names(ldata)


# generate figure -----------------------------------------------------

# pvalue thresholds, and number of hits for each threshold
df2 = lapply(ldf, `[[`, "df2") %>% lapply( function(x) 
  x %>% dplyr::filter(n>9)  %>% dplyr::filter(p > 1e-5) )

# extract the results
# in the data.frame
# n: number of hc hits 
# pv: pvalue threshold
# rest is number hits found by the methods
df = lapply(ldf, `[[`, "df") 

# results for p-value thresholds: c(0.1, 0.05, 0.01, 0.001, 1e-5, 1e-10)
df= lapply( seq(df2), function(i){
  aa = df[[i]][sapply( df2[[i]]$n, function(n) which.min(abs(df[[i]]$n-n))),]
  ns = sort(unique(c(seq(0, max(aa$n), length.out = 3)[-1], aa$n)))
  df[[i]][sapply( ns, function(n) which.min(abs(df[[i]]$n-n))),]
}) %>% do.call(what = rbind)

# ratio of recovered hc-hits
df2 = do.call(what = rbind, df2)

# melt the data 
mdf = df %>% reshape2::melt(id = c("pv","n","dt"))

# name the names
df2$dt = factor(df2$dt, 
                levels = c("qmdiab.plasma", "qmdiab.urine", "qmdiab.saliva", 
                           "brca", "rcc", "metabomxtr"),
                labels = c("QMDiab-Plasma", "QMDiab-Urine", "QMDiab-Saliva", 
                           "BRCA", "RCC", "HAPO")) 

mdf$dt = factor(mdf$dt, 
                levels = c("qmdiab.plasma", "qmdiab.urine", "qmdiab.saliva", 
                           "brca", "rcc", "metabomxtr"),
                labels = c("QMDiab-Plasma", "QMDiab-Urine", "QMDiab-Saliva", 
                           "BRCA", "RCC", "HAPO")) 
levels(mdf$variable) = c("WT + min-imp",  "WT + knn-imp", "rox")

color_codes = c("steelblue", "red", "#45A445", "orange")


# export figure 
ggplot(mdf, aes(x = n, y = value/n, color = variable)) +
  geom_vline(data = df2, aes(xintercept = n), lty = 1, color = "gray", size = 1.5, alpha = 0.5) +
  geom_hline(yintercept = 1, col = "gray", size = 2, alpha = 0.5) +
  geom_text(data = df2, aes(label =p, x = n, y = 0.42 ), inherit.aes = F, size = 2.5, angle = 90) +
  geom_line() +
  geom_point( size = 1.85 ) +
  theme_minimal() +
  theme(panel.grid = element_line(linetype = 2)) +
  facet_wrap(~dt,scales = "free_x",nrow = 2) +
  theme(strip.background = element_rect(fill = "wheat"),
        panel.background = element_rect(), 
        panel.grid = element_blank(),
        axis.ticks = element_line())  + 
  ylim(c(0.395, 1)) + 
  labs(x = "number of high-confidence hits", y = "HC-hit sensitivity", color = "") + #HCH sensitivity
  scale_color_manual(values = color_codes)

ggsave(filename = 'Fig4_recovering_hc_hits.pdf', width = 8.4, height = 6.4)


# status
cat("\nFigure saved as PDF in current working directory\n")

